name: my-actions
on: [push]
jobs:
  my-helloworld-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Say Hello World
        run: echo 'Hello World'
      
      - name: View a file
        run: |
          echo 'Viewing the file: '
          cat requirements.txt
          
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
        with:
          scan_chatbot_file_only: 'true'
